<?php

namespace App\Controllers;

use App\Models\ProfilM;

class Profil extends BaseController
{
    protected $profilm;
    function __construct()
    {
        $this->profilm = new ProfilM();
    }
    public function index()
    {
        $this->data = array('title' => 'Profil | Admin', 'breadcome' => 'Profil', 'url' => 'profil/', 'm_profil' => 'active', 'session' => $this->session);

        echo view('App\Views\profil\profil_list', $this->data);
    }

    public function ajax_request()
    {
        $list = $this->profilm->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['id'] = $rows->id;
            $row['nomor'] = $no++;
            $row['judul'] = $rows->judul;
            $row['body'] = strip_tags(substr($rows->body, 0, 100)) . ' ...';
            $data[] = $row;
        }
        $output = array(
            "total" => $this->profilm->total(),
            "totalNotFiltered" => $this->profilm->countAllResults(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function create()
    {
        $this->data = array('action' => 'insert', 'btn' => '<i class="fas fa-save"></i> Save');
        $num_of_row = $this->request->getPost('num_of_row');
        for ($x = 1; $x <= $num_of_row; $x++) {
            $data['nama'] = 'Data ' . $x;
            $this->data['form_input'][] = view('App\Views\profil\form_input', $data);
        }
        $status['html']         = view('App\Views\profil\form_modal', $this->data);
        $status['modal_title']  = 'Tambah Data Profil';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function edit()
    {
        $id = $this->request->getPost('id');
        $this->data = array('action' => 'update', 'btn' => '<i class="fas fa-edit"></i> Edit');
        foreach ($id as $ids) {
            $get = $this->profilm->find($ids);
            $data = array(
                'nama' => '<b>' . $get->judul . '</b>',
                'id' => $get->id,
                'get' => $get,
            );
            $this->data['form_input'][] = view('App\Views\profil\form_input', $data);
        }
        $status['html']         = view('App\Views\profil\form_modal', $this->data);
        $status['modal_title']  = 'Update Data Profil';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function save()
    {
        switch ($this->request->getPost('action')) {
            case 'insert':
                $nama = $this->request->getPost('id');
                $data = array();
                foreach ($nama as $key => $val) {
                    array_push($data, array(
                        'judul' => $this->request->getPost('judul')[$key],
                        'body' => $this->request->getPost('body')[$key],
                    ));
                }
                if ($this->profilm->insertBatch($data)) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Profil Tersimpan';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->profilm->errors();
                }
                echo json_encode($status);
                break;
            case 'update':
                $id = $this->request->getPost('id');
                $data = array();
                foreach ($id as $key => $val) {
                    array_push($data, array(
                        'id' => $val,
                        'judul' => $this->request->getPost('judul')[$key],
                        'body' => $this->request->getPost('body')[$key],
                    ));
                }
                if ($this->profilm->updateBatch($data, 'id')) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Profil Telah Di Ubah';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->profilm->errors();
                }
                echo json_encode($status);
                break;
            case 'delete':
                if ($this->profilm->delete($this->request->getPost('id'))) {
                    $status['type'] = 'success';
                    $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal.';
                }
                echo json_encode($status);
                break;
        }
    }
}

/* End of file Profil.php */
/* Location: ./app/controllers/Profil.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-27 03:07:59 */
/* http://harviacode.com */