<?php namespace App\Controllers;
use App\Models\Rumah_tanggaM;
class Rumah_tangga extends BaseController{
    protected $rumah_tanggam;
    function __construct(){
        $this->rumah_tanggam = new Rumah_tanggaM();
    }
    public function index(){
		$this->data = array('title'=>'Rumah_tangga | Admin','breadcome'=>'Rumah_tangga','url'=>'rumah_tangga/','m_rumah_tangga'=>'active','session'=>$this->session);
        
        echo view('App\Views\rumah_tangga\rumah_tangga_list',$this->data);
    } 
    
    public function ajax_request() {
		$list = $this->rumah_tanggam->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['id'] = $rows->id;
            $row['nomor'] = $no++;
			$row['nama'] = $rows->nama;
			$row['telp'] = $rows->telp;
			$row['alamat'] = $rows->alamat;
			$data[] = $row;
        }
        $output = array(
            "total" => $this->rumah_tanggam->total(),
            "totalNotFiltered" => $this->rumah_tanggam->countAllResults(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function create(){
		$this->data = array('action'=>'insert','btn'=>'<i class="fas fa-save"></i> Save');
        $num_of_row = $this->request->getPost('num_of_row');
        for ($x = 1; $x <= $num_of_row; $x++){
            $data['nama'] = 'Data '.$x;
            $this->data['form_input'][] = view('App\Views\rumah_tangga\form_input',$data);
        }
        $status['html']         = view('App\Views\rumah_tangga\form_modal',$this->data);
        $status['modal_title']  = 'Tambah Data Rumah_tangga';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function edit(){
		$id = $this->request->getPost('id');
        $this->data = array('action'=>'update','btn'=>'<i class="fas fa-edit"></i> Edit');
        foreach($id as $ids){
            $get = $this->rumah_tanggam->find($ids);
            $data = array(
                'nama'=>'<b>'.$get->nama.'</b>',
                'get'=>$get,
            );
            $this->data['form_input'][] = view('App\Views\rumah_tangga\form_input',$data);
        }
        $status['html']         = view('App\Views\rumah_tangga\form_modal',$this->data);
        $status['modal_title']  = 'Update Data Rumah_tangga';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function save(){
		switch ($this->request->getPost('action')) {
        case 'insert':
            $nama = $this->request->getPost('nama');
            $data = array();
            foreach($nama as $key => $val){
                array_push($data, array(
					'nama' => $this->request->getPost('nama')[$key],
					'telp' => $this->request->getPost('telp')[$key],
					'alamat' => $this->request->getPost('alamat')[$key],
				));
            }
            if ($this->rumah_tanggam->insertBatch($data)) {
                $status['type'] = 'success';
                $status['text'] = 'Data Rumah_tangga Tersimpan';
            }else{
                $status['type'] = 'error';
                $status['text'] = $this->rumah_tanggam->errors();
            }
            echo json_encode($status);
            break;
        case 'update':
            $id = $this->request->getPost('id');
            $data = array();
            foreach($id as $key => $val){
                array_push($data, array(
                    'id'=> $val,
					'nama' => $this->request->getPost('nama')[$key],
					'telp' => $this->request->getPost('telp')[$key],
					'alamat' => $this->request->getPost('alamat')[$key],
				));
            }
            if ($this->rumah_tanggam->updateBatch($data,'id')) {
                $status['type'] = 'success';
                $status['text'] = 'Data Rumah_tangga Telah Di Ubah';
            }else{
                $status['type'] = 'error';
                $status['text'] = $this->rumah_tanggam->errors();
            }
            echo json_encode($status);
            break;
        case 'delete':
            if($this->rumah_tanggam->delete($this->request->getPost('id'))){
                $status['type'] = 'success';
                $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus';
            }else{
                $status['type'] = 'error';
                $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal.';
            }
            echo json_encode($status);
            break;
        }       
    }
}

/* End of file Rumah_tangga.php */
/* Location: ./app/controllers/Rumah_tangga.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-09-07 10:46:42 */
/* http://harviacode.com */