<?php namespace App\Models;
use CodeIgniter\Model;
class AgendaM extends Model{ 
    protected $table = 'agenda';
    protected $allowedFields = array('judul','slug','isi_agenda','lokasi','id_user','published_at');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = ['judul' => 'required|max_length[100]',
		'slug' => 'required|max_length[255]',
		'isi_agenda' => 'required|max_length[65535]',
		'lokasi' => 'required|max_length[65535]',
		'id_user' => 'required|max_length[11]',
			];

    protected $validationMessages = ['judul' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 100 Karakter'],
		'slug' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 255 Karakter'],
		'isi_agenda' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 65535 Karakter'],
		'lokasi' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 65535 Karakter'],
		'id_user' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 11 Karakter'],
		];
    private function _get_datatables(){
        $column_search = array('judul','slug','isi_agenda','lokasi','id_user','published_at');
        $i = 0;
        foreach ($column_search as $item){ // loop column 
            if($_GET['search']){
                if($i===0){
                    $this->groupStart(); 
                    $this->like($item,$_GET['search']);
                }else{
                    $this->orLike($item, $_GET['search']);
                }
                if(count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if(isset($_GET['order'])){
            $this->orderBy($_GET['sort'], $_GET['order']);
        }else{
            $this->orderBy('id', 'asc');
        }
        if (!is_admin()) {
            $this->where('id_user', session('user_id'));
        }
        $this->orderBy('id', 'DESC');
        $this->select('agenda.*, u.nama_user');
        $this->join('users u', 'u.id=agenda.id_user');
    }
    public function get_datatables(){
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit,$offset);
    }
    public function total(){
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file AgendaM.php */
/* Location: ./app/models/AgendaM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-26 05:12:23 */