<?php namespace App\Models;
use CodeIgniter\Model;
class PegawaiM extends Model{ 
    protected $table = 'pegawai';
    protected $allowedFields = array('nama','nip','jk','tempat_lahir','tgl_lahir','gelar_depan','gelar_belakang','pangkat','alamat','pendidikan','lulusan','poto');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = ['nama' => 'required|max_length[250]',
		'nip' => 'required|max_length[18]',
		'jk' => 'max_length[9]',
		'tempat_lahir' => 'max_length[50]',
		'gelar_depan' => 'max_length[50]',
		'gelar_belakang' => 'max_length[50]',
		'pangkat' => 'max_length[150]',
		'alamat' => 'max_length[65535]',
		'pendidikan' => 'max_length[10]',
		'lulusan' => 'max_length[100]',
		'poto' => 'max_length[150]',
			];

    protected $validationMessages = ['nama' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 250 Karakter'],
		'nip' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 18 Karakter'],
		'jk' => ['max_length' => 'Maximal 9 Karakter'],
		'tempat_lahir' => ['max_length' => 'Maximal 50 Karakter'],
		'gelar_depan' => ['max_length' => 'Maximal 50 Karakter'],
		'gelar_belakang' => ['max_length' => 'Maximal 50 Karakter'],
		'pangkat' => ['max_length' => 'Maximal 150 Karakter'],
		'alamat' => ['max_length' => 'Maximal 65535 Karakter'],
		'pendidikan' => ['max_length' => 'Maximal 10 Karakter'],
		'lulusan' => ['max_length' => 'Maximal 100 Karakter'],
		'poto' => ['max_length' => 'Maximal 150 Karakter'],
		];
    private function _get_datatables(){
        $column_search = array('nama','nip','jk','tempat_lahir','tgl_lahir','gelar_depan','gelar_belakang','pangkat','alamat','pendidikan','lulusan','poto');
        $i = 0;
        foreach ($column_search as $item){ // loop column 
            if($_GET['search']){
                if($i===0){
                    $this->groupStart(); 
                    $this->like($item,$_GET['search']);
                }else{
                    $this->orLike($item, $_GET['search']);
                }
                if(count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if(isset($_GET['order'])){
            $this->orderBy($_GET['sort'], $_GET['order']);
        }else{
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables(){
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit,$offset);
    }
    public function total(){
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file PegawaiM.php */
/* Location: ./app/models/PegawaiM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-07-15 03:45:19 */