<?php namespace App\Models;
use CodeIgniter\Model;
class PotensiM extends Model{ 
    protected $table = 'potensi';
    protected $allowedFields = array('bidang','judul','isi_potensi');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = ['bidang' => 'required|max_length[11]',
		'judul' => 'required|max_length[100]',
		'isi_potensi' => 'required|max_length[65535]',
			];

    protected $validationMessages = ['bidang' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 11 Karakter'],
		'judul' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 100 Karakter'],
		'isi_potensi' => ['required' => 'tidak boleh kosong','max_length' => 'Maximal 65535 Karakter'],
		];
    private function _get_datatables(){
        $column_search = array('bidang','judul','isi_potensi');
        $i = 0;
        foreach ($column_search as $item){ // loop column 
            if($_GET['search']){
                if($i===0){
                    $this->groupStart(); 
                    $this->like($item,$_GET['search']);
                }else{
                    $this->orLike($item, $_GET['search']);
                }
                if(count($column_search) - 1 == $i)
                    $this->groupEnd();
            }
            $i++;
        }
        if(isset($_GET['order'])){
            $this->orderBy($_GET['sort'], $_GET['order']);
        }else{
            $this->orderBy('id', 'asc');
        }
    }
    public function get_datatables(){
        $this->_get_datatables();
        $limit = isset($_GET['limit']) ? $_GET['limit'] : 0;
        $offset = isset($_GET['offset']) ? $_GET['offset'] : 0;
        return $this->findAll($limit,$offset);
    }
    public function total(){
        $this->_get_datatables();
        if ($this->tempUseSoftDeletes) {
            $this->where($this->table . '.' . $this->deletedField, null);
        }
        return $this->get()->getNumRows();
    }
}
/* End of file PotensiM.php */
/* Location: ./app/models/PotensiM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-24 04:45:25 */